name: Run PHPCS on pull requests for main branches
on:
  pull_request:
    branches:
      - master
      - preprod
      - develop
jobs:
  phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: rtCamp/action-phpcs-code-review@master
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
